### ISSUE TITLE
target is usually not wanted in version control

### ISSUE THREAD

**Issue by markstur** [IBM/appmod-resorts#5]
Might be debatable, but I think the general consensus is that the target dir should not be in version control.  It is built and gets in the way.  I think we want that war in data/examples anyway.

**Comment by danbanta** [comment]
I will make the change. We will also generate a zip through TA. I will place the generated zip in data/examples as well.

**Comment by markstur** [comment]
Was fixed with https://github.com/IBM/appmod-resorts/commit/f1abb59d7d2d6362474f9809a6d898c73644581b
